const menu=document.querySelector('.menu');const mobileNav=document.querySelector('#mobile-nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));mobileNav.hidden=open;});mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileNav.hidden=true;menu.setAttribute('aria-expanded','false');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!mobileNav.hidden){mobileNav.hidden=true;menu.setAttribute('aria-expanded','false');menu.focus();}});
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
if('IntersectionObserver' in window){document.body.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}});},{threshold:.08});document.querySelectorAll('.section-label,.food-story,.values article,.intro-grid,.homes-grid,.home-details,.step-list li,.section-heading').forEach(el=>{el.classList.add('reveal');observer.observe(el);});}
let tick=false;const progress=()=>{const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.reading-progress').style.transform=`scaleX(${max>0?scrollY/max:0})`;document.body.classList.toggle('scrolled',scrollY>30);tick=false;};window.addEventListener('scroll',()=>{if(!tick){requestAnimationFrame(progress);tick=true;}},{passive:true});progress();
const slides=[...document.querySelectorAll('.hero-slide')];let slideIndex=0,heroVisible=true;const heroObserver=new IntersectionObserver(([entry])=>{heroVisible=entry.isIntersecting;});heroObserver.observe(document.querySelector('.hero'));setInterval(()=>{if(document.hidden||!heroVisible)return;const previous=slideIndex;slideIndex=(slideIndex+1)%slides.length;slides.forEach((img,index)=>{img.classList.toggle('previous',index===previous);img.classList.toggle('active',index===slideIndex)});},6500);
const track=document.querySelector('.food-track');document.querySelector('.gallery-prev').addEventListener('click',()=>track.scrollBy({left:-track.clientWidth*.85,behavior:reduced.matches?'instant':'smooth'}));document.querySelector('.gallery-next').addEventListener('click',()=>track.scrollBy({left:track.clientWidth*.85,behavior:reduced.matches?'instant':'smooth'}));
const dialog=document.querySelector('.photo-dialog');document.querySelectorAll('.photo-open').forEach(button=>button.addEventListener('click',()=>{dialog.querySelector('img').src=button.dataset.photo;dialog.querySelector('img').alt=button.querySelector('img').alt;dialog.querySelector('p').textContent=button.dataset.caption;dialog.showModal();document.body.classList.add('modal-open');}));dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));

const welcome=document.querySelector('.welcome-screen');if(document.documentElement.classList.contains('welcome-ready')){let finished=false;const pageParts=[document.querySelector('header'),document.querySelector('#main'),document.querySelector('footer')];pageParts.forEach(el=>el.inert=true);const finishWelcome=()=>{if(finished)return;finished=true;document.documentElement.classList.add('welcome-leaving');try{sessionStorage.setItem('happiness-welcomed-v2','1')}catch(e){}setTimeout(()=>{document.documentElement.classList.remove('welcome-ready','welcome-opening','welcome-leaving');pageParts.forEach(el=>el.inert=false);welcome.remove();progress();},750)};welcome.querySelector('button').addEventListener('click',finishWelcome);document.addEventListener('keydown',e=>{if(e.key==='Escape')finishWelcome()});setTimeout(()=>document.documentElement.classList.add('welcome-opening'),650);setTimeout(finishWelcome,2300);setTimeout(()=>pageParts.forEach(el=>el.inert=false),5800)}else{welcome.remove()}
